ATTACH TABLE _ UUID 'e7383ce2-e226-4382-9a20-20884627ef09'
(
    `psn_no` String COMMENT '参保人唯一编号',
    `psn_name` String COMMENT '参保人姓名',
    `gend` String,
    `psn_cert_type` String,
    `certno` String COMMENT '身份证号码',
    `brdy` DateTime,
    `age` Float64,
    `psn_type` String,
    `tel` String,
    `addr` String,
    `cvlserv_flag` String,
    `cvlserv_lv` String,
    `sp_psn_type` String,
    `sp_psn_type_lv` String,
    `insu_admdvs` String,
    `admdvs_prv` String,
    `admdvs_prvname` String,
    `admdvs_city` String,
    `admdvs_cityname` String,
    `emp_no` String,
    `emp_name` String,
    `emp_type` String,
    `econ_type` String,
    `insutype` String,
    `fixmedins_code` String COMMENT '医药机构/医院编码',
    `fixmedins_name` String COMMENT '医药机构名称',
    `medinslv` String,
    `hosp_lv` String COMMENT '医院等级',
    `hosp_natu_code` String,
    `fix_blng_admdvs` String,
    `fix_blng_admdvs_city` String,
    `pay_loc` String,
    `med_typecode` String,
    `med_type` String COMMENT '医疗类别 (门诊/住院/药店)',
    `med_bigtype` String,
    `mdtrt_id` String,
    `ipt_otp_no` String,
    `start_date` DateTime COMMENT '入院/开始日期',
    `end_date` DateTime COMMENT '出院/结束日期',
    `adm_dept_code` String,
    `adm_dept_name` String,
    `dscg_dept_codg` String,
    `dscg_dept_name` String,
    `ipt_days` String COMMENT '住院天数',
    `adm_bed` String,
    `chfpdr_code` String,
    `chfpdr_name` String,
    `dise_no` String,
    `dise_name` String COMMENT '诊断名称/疾病描述',
    `oprn_oprt_code` String,
    `oprn_oprt_name` String,
    `setl_id` String,
    `setl_time` DateTime COMMENT '结算时间',
    `medfee_sumamt` Float64 COMMENT '医疗费总金额',
    `hifp_pay` Float64 COMMENT '统筹基金支付金额 (医保报销核心)',
    `fund_pay_sumamt` Float64 COMMENT '基金支付总额 (含统筹及各类补助)',
    `acct_pay` Float64 COMMENT '个人账户支付金额',
    `cash_payamt` Float64 COMMENT '个人现金支付金额',
    `balc` Float64,
    `inscp_amt` Float64,
    `hi_agre_sumfee` Float64,
    `acct_mulaid_pay` Float64,
    `bydise_setl_payamt` Float64,
    `cvlserv_pay` Float64,
    `maf_pay` Float64 COMMENT '医疗救助资金支付',
    `year` String,
    `updt_time` DateTime,
    `crte_time` DateTime,
    `dwh_created_dt` DateTime,
    `src_dt` String,
    `src_prv` String,
    `vali_flag` String,
    `uyear` String,
    `uhalfyear` String,
    `uquarter` String,
    `umonth` String,
    `uweek` String,
    `prv` String,
    `city` String,
    `admdvs_code` Int64 COMMENT '行政区划代码',
    `admdvs_name` String COMMENT '行政区划名称',
    `adm_caty` String,
    `inhosp_stas` Int64,
    `refd_setl_flag` Int64,
    `setl_type` Int64,
    `fulamt_ownpay_amt` Int64,
    `hifmi_pay` Int64,
    `hifob_pay` Int64,
    `hifdm_pay` Int64,
    `othfund_pay` Int64,
    `admdvs_district` Int64
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192
